name: actions
on:
  push:
jobs:
  test-actions:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: ls
        run: ls
      - name: hello-world-action
        id: hello-world-action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Sunil"
      - name: time
        run: echo "'greeting it:', ${{ steps.hello-world-action.outputs.time }}" 
      - name: docker action
        uses: docker://hello-world:latest
  
        
